spring:
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?createDatabaseIfNotExist=true
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
